GET https://api.weixin.qq.com/sns/jscode2session?appid=wxaa7a5cf0a34b571f
                                            &secret=b923efc0067eafa7e0938a2c3f8e714f
                                            &js_code=053KFSkl2lrYn54XA2ol2zNDrY3KFSk-
                                            &grant_type=authorization_code

###
POST https://hvac2.anylink.io:8443/

###
